# -*- coding: utf-8 -*-
"""penguin task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F89KPRQh8pBTAKmvkJCrIoQ7O_hG9Jh3
"""

import numpy as np

courses = ["English Grammar","Mathematics","Physics","Chemistry","Biology"]
teachers = ["John Smith","Lara Gilbert","Johanna Kabir","Danniel Robertson","Larry Cooper"]
a=[]
day=[0,0,0,0,0]
while True:
  print(" A. Create Routine\n B. Show Routine\n C. List Courses with Teachers Name\n E. Exit")
  x=input()
  if x =='a' or x == 'A':
    for i in range(0,len(courses)):
      print(i,"."+courses[i])
    course=int(input("How many courses you want to add:"))
    for j in range(0,course):
      c=list(map(int, input().split()))
      day[c[0]]=day[c[0]]+1
      if(day[c[0]]>4):
        print("No slot left for that day")
        day[c[0]]=day[c[0]]-1
      a.append(c)
      print(a)
  elif x =='b' or x == 'B':
    for r in range(0,len(a)):
      print(a[r][0],a[r][1], courses[a[r][2]])
    
  elif x =='c' or x == 'C':
    for i in range(0,len(courses)):
      print(i,"."+courses[i]+","+teachers[i])

  elif x =='e' or x == 'E':
    break



